// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrjK6DbGM_sgKRxkjBjlsoudzKq_UG6M',
    appId: '1:324906958737:web:5edd3229ffcbd7083d2430',
    messagingSenderId: '324906958737',
    projectId: 'rentalumm',
    authDomain: 'rentalumm.firebaseapp.com',
    storageBucket: 'rentalumm.appspot.com',
    measurementId: 'G-TCT32JG7N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4hUrZjDQVs2ZxYuGuQCPLCdqmF2-BNY',
    appId: '1:324906958737:android:ae5053dc66b296033d2430',
    messagingSenderId: '324906958737',
    projectId: 'rentalumm',
    storageBucket: 'rentalumm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6cTj0N1GpWAE2YE9SV5qnBbecHKwXHw',
    appId: '1:324906958737:ios:3b2194218c89af233d2430',
    messagingSenderId: '324906958737',
    projectId: 'rentalumm',
    storageBucket: 'rentalumm.appspot.com',
    iosClientId: '324906958737-fotsbt6180veeq0r7de10gv0qsk62btj.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikumMobile',
  );
}
